"""TOML project config loader.

Reads a swift-doc.toml (or any named) config file that can hold all
CLI parameters plus ignore lists for calls and types.
"""

import os
import sys

if sys.version_info >= (3, 11):
    import tomllib
else:
    import tomli as tomllib


# Keys that can appear at the top level of a TOML config.
_TOP_LEVEL_KEYS = {
    "root_dir", "lang", "output_folder", "cache_dir",
    "format", "group_by", "style", "ai", "analyse_dirs", "type",
    "local_table",
}

# Keys that appear under [ignore]
_IGNORE_KEYS = {"calls", "types"}

# Default config filename to auto-discover
DEFAULT_CONFIG_NAME = "swift-doc.toml"

# Template TOML config generated by `swift-doc createconfig`
DEFAULT_CONFIG_TEMPLATE = '''\
# swift-doc.toml -- generated by `swift-doc createconfig`
# Uncomment and modify fields as needed.

type = "moduledesign"       # document type: "moduledesign"
root_dir = "."

# --- Output options ---
# lang = "auto"              # "auto" | "c" | "ada"
# output_folder = "out"      # where generated docs land
# format = "docx"            # "docx" | "markdown"
# group_by = "file"          # "file" | "function"
# style = "plain"            # "plain" | "slate" | "fearless" | "red" | "table"
# local_table = "no"          # "yes" | "no": append local types table per document

# --- Extraction options ---
# ai = "off"                 # "off" | "on"
# cache_dir = ".analysis"    # override the platform default cache dir
# analyse_dirs = []          # scope docs to specific subdirectories (repeatable)
# Example:
#   analyse_dirs = ["src/core", "src/utils"]
#   analyse_dirs = ["src/main.c"]              # single file

# --- Ignore lists ---
# Example:
#   [ignore]
#   calls = ["memcpy", "memset", "free"]
#   types = ["noisy_type", "internal_t"]
#   kinds = ["typedef", "enum"]
[ignore]
calls = []                   # function names to exclude from call graphs
types = []                   # type names to skip during extraction
kinds = []                   # type kinds to skip: C: struct, union, enum, typedef; Ada: record, enumeration, access, array, derived, subtype, modular, fixed_point, decimal_fixed_point, float, interface, private, type

# --- Preprocessor defines ---
# Example:
#   [define]
#   macros = ["DEBUG", "FEATURE_X", "VERSION=2"]
[define]
macros = []                  # preprocessor macro names to mark as defined

# --- Section toggles ---
# Set any key to false to skip that section in generated docs.
# Example:
#   [sections]
#   local_data = false
#   algorithm = false
[sections]
module_description = true
module_summary = true
inputs = true
outputs = true
global_data = true
local_data = true
algorithm = true
interface = true
appendix = true
'''


def load_toml(path: str) -> dict:
    """Parse a TOML config file and return a flat config dict.

    Returns a dict with string keys.  Keys not present in the file
    are set to None so that the caller can distinguish "not set"
    from "set to an empty value".

    Schema returned::

        {
            "root_dir": str | None,
            "lang": str | None,
            "output_folder": str | None,
            "cache_dir": str | None,
            "format": str | None,
            "group_by": str | None,
            "style": str | None,
            "ai": str | None,
            "analyse_dirs": list[str] | None,
            "ignore_calls": list[str] | None,
            "ignore_types": list[str] | None,
        }
    """
    with open(path, "rb") as f:
        raw = tomllib.load(f)

    config: dict = {}

    # Top-level keys
    for key in _TOP_LEVEL_KEYS:
        val = raw.get(key)
        if val is not None and not isinstance(val, str) and key not in ("analyse_dirs",):
            val = str(val)
        config[key] = val

    # type defaults to "moduledesign" for backward compat
    if config.get("type") is None:
        config["type"] = "moduledesign"

    # analyse_dirs can be a list of strings
    config["analyse_dirs"] = raw.get("analyse_dirs")

    # [ignore] section
    ignore = raw.get("ignore", {})
    config["ignore_calls"] = ignore.get("calls")
    config["ignore_types"] = ignore.get("types")
    config["ignore_kinds"] = ignore.get("kinds")

    # [define] section
    define = raw.get("define", {})
    config["define_macros"] = define.get("macros")

    # [sections] section — dict of bool toggles, defaults to True
    _SECTION_KEYS = {
        "module_description", "module_summary", "inputs", "outputs",
        "global_data", "local_data", "algorithm", "interface", "appendix",
    }
    sections_raw = raw.get("sections", {})
    sections = {}
    for key in _SECTION_KEYS:
        sections[key] = sections_raw.get(key, True)
    config["sections"] = sections

    return config


def find_config(search_dir: str) -> str | None:
    """Look for swift-doc.toml in *search_dir*.

    Returns the absolute path if found, or None.
    """
    candidate = os.path.join(search_dir, DEFAULT_CONFIG_NAME)
    if os.path.isfile(candidate):
        return os.path.abspath(candidate)
    return None
